package sopqua.util.arromaniyyah;

public enum ArabicGrapheme {
    FATHAH, KASRAH, DAMMAH, HANJARIYYAH, ALIF_MADDAH, ALIF_WASLAH, SUKUN, FATHAH_TANWIN,
    KASRAH_TANWIN, DAMMAH_TANWIN, SHADDAH, YA, MAQSURAH, WAW, HA, NUN, MIM, LAM, KAF, QAF,
    FA, GHAYN, AYN, ZA, TTA, DAD, SAD, SHIN, SIN, ZAY, RA, DHAL, DAL, KHA, HHA, JIM, THA, TA,
    BA, ALIF, HAMZAH, MARBUTAH, MEDIAL_IY_HAMZAH, MEDIAL_AY_HAMZAH, AL, MEDIAL_HAMZAH_I,
    INITIAL_HAMZAH_I, INITIAL_HAMZAH_U, INITIAL_HAMZAH_A, MEDIAL_HAMZAH_U_ON_YA,
    MEDIAL_HAMZAH_A_ON_YA, MEDIAL_HAMZAH_U_ON_WAW, MEDIAL_HAMZAH_A_ON_WAW, MEDIAL_HAMZAH_A_ON_ALIF,
    FINAL_HAMZAH_ON_YA, FINAL_HAMZAH_ON_WAW, FINAL_HAMZAH_ABOVE_ALIF, FINAL_HAMZAH_BELOW_ALIF
}